### ISSUE TITLE
Update to GlassFish 4.0-b66

### ISSUE THREAD

**Issue by brunoborges** [javaee/jersey-hol-sse-websocket#1]
If running this HOL with GF4b66, the user will face an issue with WebSockets.

The HOL expects @WebSocketEndpoint to have the attribute "path". This doesn't exist anymore on the latest version of the API.

Update the POM following these versions: https://github.com/brunoborges/hol-sse-websocket/commit/d70d92f27a41d15c3b2ea12e69086a4cefabde39#L0L32

Update the lab-guide to use @WebSocketEndpoint( value = "/websockets/" ...

**Comment by pavelbucek** [comment]
Hi Bruno,

WebSocketEndpoint.path was renamed to WebSocketEndpoint.value and it was 
moved from javax.net.websocket package to just javax.websocket

Some other changes will be done in the API soon, so I'm little reluctant 
to commit to update this HOL soon, but we definitely plan to do that 
(when websocket become more stable).

Pavel
